### ISSUE TITLE
Yotta can not find mbedtls

### ISSUE THREAD

**Issue by dymo** [ARMmbed/mbedtls#269]
Installing with Yotta fails:
```
d:\Temp\mbedtls>yotta target frdm-k64f-gcc
d:\Temp\mbedtls>yotta install mbedtls
info: get versions for mbedtls
Traceback (most recent call last):
  File "C:\Python27\Scripts\yotta-script.py", line 9, in <module>
    load_entry_point('yotta==0.7.0', 'console_scripts', 'yotta')()
  File "C:\Python27\lib\site-packages\yotta\main.py", line 229, in main
    status = args.command(args, following_args)
  File "C:\Python27\lib\site-packages\yotta\install.py", line 63, in execCommand
    return installComponent(args)
  File "C:\Python27\lib\site-packages\yotta\install.py", line 194, in installComponent
    working_directory = path
  File "C:\Python27\lib\site-packages\yotta\lib\access.py", line 354, in satisfyVersion
    return satisfyVersionByInstalling(name, version_required, working_directory, type=type)
  File "C:\Python27\lib\site-packages\yotta\lib\access.py", line 296, in satisfyVersionByInstalling
    v = latestSuitableVersion(name, version_required, _registryNamespaceForType(type))
  File "C:\Python27\lib\site-packages\yotta\lib\access.py", line 110, in latestSuitableVersion
    vers = remote_component.availableVersions()
  File "C:\Python27\lib\site-packages\yotta\lib\registry_access.py", line 392, in availableVersions
    return _listVersions(self.namespace, self.name)
  File "C:\Python27\lib\site-packages\yotta\lib\registry_access.py", line 206, in _listVersions
    'Check that the name is correct, and that it has been published.') % (name, namespace)
yotta.lib.access_common.Unavailable: mbedtls does not exist in the modules registry. Check that the name is correct, and
 that it has been published.
```

**Comment by mpg** [comment]
As the error message suggests, the module hasn't been published to the public yotta registry yet. It will be published at the same time as the rest of mbed OS.

The Readme does not reflect the current state of things, but the state after publication. Currently the only way to use the yotta module is to generate it using the provided script. Note that to build it for the k64f, you'll need other mbed OS modules that haven't been published yet either.
