### ISSUE TITLE
mbedtls-2.7.13 crashes in glibc with "double free or corruption"

### ISSUE THREAD

**Issue by neoxic** [ARMmbed/mbedtls#3544]
Hello everyone,
First of all, thank you for the brilliant work that Mbed TLS is!

We're observing unexpected behaviour of **mbedtls-2.7.13** in our server environment. We deliberately postponed upgrading to **2.7.16** in order to help investigate potential hidden issues (if any) since scanning the ChangeLog didn't reveal obvious reasons to upgrade not was there any concern of misuse on our side. Diff'ing `library/bignum.c` reveals a bunch of changes that might potentially be a fix to the issue. Anyways, please see below...

```
#0  0x00007f1a386562c7 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:55
#1  0x00007f1a386579b8 in __GI_abort () at abort.c:90
#2  0x00007f1a38698e17 in __libc_message (do_abort=do_abort@entry=2, fmt=fmt@entry=0x7f1a387aa7f8 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/unix/sysv/linux/libc_fatal.c:196
#3  0x00007f1a386a1609 in malloc_printerr (ar_ptr=0x7f1a1c000020, ptr=<optimized out>, str=0x7f1a387aa920 "double free or corruption (!prev)", action=3) at malloc.c:5004
#4  _int_free (av=0x7f1a1c000020, p=<optimized out>, have_lock=0) at malloc.c:3843
#5  0x00007f1a39a7b7dd in mbedtls_mpi_grow (X=X@entry=0x1c84268, nblimbs=nblimbs@entry=256) at /usr/src/debug/mbedtls-2.7.13/library/bignum.c:135
#6  0x00007f1a39a7cb6a in mbedtls_mpi_mul_mpi (X=X@entry=0x1c84268, A=0x7f1a34d65600, A@entry=0x1c84268, B=0x7f1a34d65620, B@entry=0x1c84268) at /usr/src/debug/mbedtls-2.7.13/library/bignum.c:1343
#7  0x00007f1a39a9e5a2 in rsa_prepare_blinding (p_rng=0x64f2c0 <net::tls::drbg>, f_rng=0x405dc0 <mbedtls_ctr_drbg_random@plt>, ctx=0x1c84150) at /usr/src/debug/mbedtls-2.7.13/library/rsa.c:720
#8  mbedtls_rsa_private (ctx=ctx@entry=0x1c84150, f_rng=f_rng@entry=0x405dc0 <mbedtls_ctr_drbg_random@plt>, p_rng=p_rng@entry=0x64f2c0 <net::tls::drbg>, input=input@entry=0x7f1a18051f4e "",
    output=output@entry=0x7f1a18056d60 "") at /usr/src/debug/mbedtls-2.7.13/library/rsa.c:863
#9  0x00007f1a39a9f9d2 in mbedtls_rsa_rsassa_pkcs1_v15_sign (ctx=0x1c84150, f_rng=0x405dc0 <mbedtls_ctr_drbg_random@plt>, p_rng=0x64f2c0 <net::tls::drbg>, mode=<optimized out>,
    md_alg=<optimized out>, hashlen=<optimized out>,
    hash=0x7f1a34d65900 "\016\307Nx\027J\206(V_\301\347\242\300ɮ\231\217\033w\277G!\r\344\376Nw\006\250\337\"\037Me[\236D>\361`\204", <incomplete sequence \367>, sig=0x7f1a18051f4e "")
    at /usr/src/debug/mbedtls-2.7.13/library/rsa.c:1943
#10 0x00007f1a39cd302c in ssl_write_server_key_exchange (ssl=0x7f1a18008028) at /usr/src/debug/mbedtls-2.7.13/library/ssl_srv.c:3203
#11 mbedtls_ssl_handshake_server_step (ssl=ssl@entry=0x7f1a18008028) at /usr/src/debug/mbedtls-2.7.13/library/ssl_srv.c:4057
#12 0x00007f1a39cd7e43 in mbedtls_ssl_handshake_step (ssl=ssl@entry=0x7f1a18008028) at /usr/src/debug/mbedtls-2.7.13/library/ssl_tls.c:6841
#13 0x00007f1a39cd7eb0 in mbedtls_ssl_handshake (ssl=ssl@entry=0x7f1a18008028) at /usr/src/debug/mbedtls-2.7.13/library/ssl_tls.c:6861
#14 0x00007f1a39cdee03 in mbedtls_ssl_read (ssl=0x7f1a18008028, buf=0x7f1a1801f3d0 "\210", len=4) at /usr/src/debug/mbedtls-2.7.13/library/ssl_tls.c:7084
...
```

In our environment, `mbedtls_ssl_read()` is used in multiple threads (each with a separate ssl context of course) with a shared read-only `mbedtls_ssl_config` exactly as in `programs/ssl/ssl_pthread_server.c`. A server certificate/private key is stored in PKCS8/DER format and parsed with the `mbedtls_x509_crt_parse()`/`mbedtls_pk_parse_key()` functions as is done in the examples. So nothing fancy here usage-wise.

**Comment by neoxic** [comment]
We're also currently observing a daemon that no client can establish a TLS connection with presumably due to some Mbed TLS state corruption. Please let me know if we can provide some insight via live debugging.

**Comment by neoxic** [comment]
Ok, upon a thorough look, it looks like `MBEDTLS_THREADING_C` and `MBEDTLS_THREADING_PTHREAD` are disabled by default in our case. I guess the root of the problem might be on our side. I'll report back and close this issue if that's the case.

**Comment by neoxic** [comment]
To summarize, the `mbedtls` package installed on Centos 7 via EPEL *cannot* be used in a multithreaded program because it is built with the default settings intended for embedded single process use. Presumably, Fedora is affected too. Unaware users who run Mbed TLS in multithreaded environment without the multithreading layer enabled are sitting on a ticking time bomb, hence this could be a serious security issue. This issue will be reported to the maintainers of the corresponding package.
