### ISSUE TITLE
mbedtls_debug_print_mpi crashes on 0

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARMmbed/mbedtls#4608]
This bug was originally reported by @lhuang04 in #4578. I'm creating an issue to facilitate tracking.

Steps to reproduce (confirmed at 72dcd4e4f16d9d78ab16be57c7b8e9a239a6c961, but I think the TLS/x25519 part has existed ever since TLS started supporting x52219 and the debug_mpi part since PolarSSL):
```
make
programs/ssl/ssl_server2 debug_level=3 &
programs/ssl/ssl_client2 curves=x25519
```

Expected behavior: a TLS connection happens normally, using x25519 for the key exchange.

Actual behavior:
```
…
ssl_srv.c:3665: |2| => write server key exchange
ssl_srv.c:3443: |2| ECDHE curve: x25519
ssl_srv.c:3468: |3| value of 'ECDH: Q(X)' (254 bits) is:
ssl_srv.c:3468: |3|  3d 3f 0e fc 6e 35 c8 53 53 d8 b7 59 20 95 b2 5a
ssl_srv.c:3468: |3|  60 1c 16 ea b7 9a cb ff dd 04 98 46 b6 55 8b 86
[1]    2345374 segmentation fault (core dumped)  programs/ssl/ssl_server2 debug_level=3
```

An UBSan or Msan build gives a backtrace:
```
source/library/debug.c:236:13: runtime error: applying non-zero offset 18446744073709551608 to null pointer
    #0 0x4d449d in mbedtls_debug_print_mpi library/debug.c:236:13
    #1 0x4d3b1f in mbedtls_debug_print_ecp library/debug.c:213:5
    #2 0x4f2beb in ssl_prepare_server_key_exchange library/ssl_srv.c:3468:9
    #3 0x4f2beb in ssl_write_server_key_exchange library/ssl_srv.c:3703:15
    #4 0x4f2beb in mbedtls_ssl_handshake_server_step library/ssl_srv.c:4736:19
    #5 0x511461 in mbedtls_ssl_handshake library/ssl_tls.c:5815:15
    #6 0x4ca075 in main programs/ssl/ssl_server2.c:3155:20
    #7 0x7fb5c1ebc0b2 in __libc_start_main /build/glibc-eX1tMB/glibc-2.31/csu/../csu/libc-start.c:308:16
    #8 0x41c47d in _start (/home/gilpes01/z/dev/mbedtls/main/build-asan/programs/ssl/ssl_server2+0x41c47d)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior source/library/debug.c:236:13 in 
```

As analyzed by @lhuang04, `mbedtls_debug_print_mpi` does not correctly handle the case of an MPI such that `X->n == 0`, which is a valid representation of 0.

In addition, `mbedtls_debug_print_ecp` shouldn't be printing 0 here, but that's [more of a cosmetic issue](https://github.com/ARMmbed/mbedtls/issues/4609).

**Comment by gilles-peskine-arm** [comment]
Fix posted in https://github.com/ARMmbed/mbedtls/pull/4604. I'll make backports once it's been reviewed.
