### ISSUE TITLE
CMake parallel build failure

### ISSUE THREAD

**Issue by chenrui333** [ARMmbed/mbedtls#5374]
### Summary

👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>build error</summary>

```
[ 95%] Generating suites/test_suite_psa_crypto_generate_key.generated.data, suites/test_suite_psa_crypto_not_supported.generated.data, suites/test_suite_psa_crypto_storage_format.current.data, suites/test_suite_psa_crypto_storage_format.v0.data cd /tmp/mbedtls-20211218-25035-1043085/mbedtls-mbedtls-3.1.0 && /opt/homebrew/opt/python@3.10/bin/python3 /tmp/mbedtls-20211218-25035-1043085/mbedtls-mbedtls-3.1.0/tests/../tests/scripts/generate_psa_tests.py --directory /tmp/mbedtls-20211218-25035-1043085/mbedtls-mbedtls-3.1.0/build/tests/suites Traceback (most recent call last): File "/tmp/mbedtls-20211218-25035-1043085/mbedtls-mbedtls-3.1.0/tests/scripts/generate_test_code.py", line 1142, in <module> main() File "/tmp/mbedtls-20211218-25035-1043085/mbedtls-mbedtls-3.1.0/tests/scripts/generate_test_code.py", line 1133, in main generate_code(funcs_file=args.funcs_file, data_file=args.data_file, File "/tmp/mbedtls-20211218-25035-1043085/mbedtls-mbedtls-3.1.0/tests/scripts/generate_test_code.py", line 1055, in generate_code raise IOError("ERROR: %s [%s] not found!" % (name, path)) OSError: ERROR: Data file [/tmp/mbedtls-20211218-25035-1043085/mbedtls-mbedtls-3.1.0/build/tests/suites/test_suite_psa_crypto_storage_format.v0.data] not found! make[2]: *** [tests/test_suite_psa_crypto_storage_format.v0.c] Error 1
```

</details>

### System information

Mbed TLS version (number or commit id): 3.1.0
Operating system and version: macOS 12

### Expected behavior

build successfully

### Steps to reproduce

- untar 3.1.0 tarball file
- `cmake -S . -B build -DUSE_SHARED_MBEDTLS_LIBRARY=On -DPython3_EXECUTABLE=/opt/homebrew/opt/python@3.10/bin/python3 -DCMAKE_INSTALL_RPATH=@loader_path/../lib -DCMAKE_INSTALL_PREFIX=/opt/homebrew/Cellar/mbedtls/3.1.0 -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -DBUILD_TESTING=OFF -DCMAKE_OSX_SYSROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk`
- `cmake --build build`

### Additional information

full build log, https://github.com/Homebrew/homebrew-core/runs/4571515113
relates to Homebrew/homebrew-core#91501
relates to Homebrew/homebrew-core#92136

**Comment by gilles-peskine-arm** [comment]
I can't reproduce this: I tried (also on an M1 Mac with Homebrew installed) and `cmake --build build` completed successfully.

`test_suite_psa_crypto_generate_key.generated.data` is present in the release, so it doesn't _need_ to be generated. This is a generated file that only depends on other source files, not on the library configuration or the platform. We no longer keep such files in the git tree in the development branch, but we add them to releases.

Looking at the release content, it seems that we aren't changing the build scripts to not attempt to rebuild those files. The file timestamps in the official archive are the time the archive was generated, so if they're preserved on extraction, they should match and `make` shouldn't attempt to re-generate the file. But if the timestamps don't match for some reason, the build may attempt to re-generate those files. That's not the behavior you intended. However, regenerating those files should still work _if not cross-compiling_ (the generation of `test_suite_psa_crypto_generate_key.generated.data` needs to compile a C program that runs on the host).

Looking at the logs, I see another problem, or maybe two problems.

```
2021-12-18T22:37:37.9204050Z [ 95%] Generating test_suite_psa_crypto_storage_format.v0.c
2021-12-18T22:37:37.9207770Z cd /tmp/mbedtls-20211218-25035-1043085/mbedtls-mbedtls-3.1.0/build/tests && /opt/homebrew/opt/python@3.10/bin/python3 /tmp/mbedtls-20211218-25035-1043085/mbedtls-mbedtls-3.1.0/tests/scripts/generate_test_code.py -f /tmp/mbedtls-20211218-25035-1043085/mbedtls-mbedtls-3.1.0/tests/suites/test_suite_psa_crypto_storage_format.function -d /tmp/mbedtls-20211218-25035-1043085/mbedtls-mbedtls-3.1.0/build/tests/suites/test_suite_psa_crypto_storage_format.v0.data -t /tmp/mbedtls-20211218-25035-1043085/mbedtls-mbedtls-3.1.0/tests/suites/main_test.function -p /tmp/mbedtls-20211218-25035-1043085/mbedtls-mbedtls-3.1.0/tests/suites/host_test.function -s /tmp/mbedtls-20211218-25035-1043085/mbedtls-mbedtls-3.1.0/tests/suites --helpers-file /tmp/mbedtls-20211218-25035-1043085/mbedtls-mbedtls-3.1.0/tests/suites/helpers.function -o .
2021-12-18T22:37:37.9212570Z Deleting primary custom command output "/tmp/mbedtls-20211218-25035-1043085/mbedtls-mbedtls-3.1.0/build/tests/suites/test_suite_psa_crypto_generate_key.generated.data" because another output "/tmp/mbedtls-20211218-25035-1043085/mbedtls-mbedtls-3.1.0/build/tests/suites/test_suite_psa_crypto_storage_format.v0.data" does not exist.
2021-12-18T22:37:37.9214930Z /Applications/Xcode.app/Contents/Developer/usr/bin/make  -f tests/CMakeFiles/test_suite_psa_crypto_storage_format.current.dir/build.make tests/CMakeFiles/test_suite_psa_crypto_storage_format.current.dir/build
2021-12-18T22:37:37.9216780Z [ 95%] Generating suites/test_suite_psa_crypto_generate_key.generated.data, suites/test_suite_psa_crypto_not_supported.generated.data, suites/test_suite_psa_crypto_storage_format.current.data, suites/test_suite_psa_crypto_storage_format.v0.data
2021-12-18T22:37:37.9219220Z cd /tmp/mbedtls-20211218-25035-1043085/mbedtls-mbedtls-3.1.0 && /opt/homebrew/opt/python@3.10/bin/python3 /tmp/mbedtls-20211218-25035-1043085/mbedtls-mbedtls-3.1.0/tests/../tests/scripts/generate_psa_tests.py --directory /tmp/mbedtls-20211218-25035-1043085/mbedtls-mbedtls-3.1.0/build/tests/suites
2021-12-18T22:37:37.9220640Z Traceback (most recent call last):
2021-12-18T22:37:37.9221570Z   File "/tmp/mbedtls-20211218-25035-1043085/mbedtls-mbedtls-3.1.0/tests/scripts/generate_test_code.py", line 1142, in <module>
2021-12-18T22:37:37.9222270Z     main()
2021-12-18T22:37:37.9223090Z   File "/tmp/mbedtls-20211218-25035-1043085/mbedtls-mbedtls-3.1.0/tests/scripts/generate_test_code.py", line 1133, in main
2021-12-18T22:37:37.9223920Z     generate_code(funcs_file=args.funcs_file, data_file=args.data_file,
2021-12-18T22:37:37.9224970Z   File "/tmp/mbedtls-20211218-25035-1043085/mbedtls-mbedtls-3.1.0/tests/scripts/generate_test_code.py", line 1055, in generate_code
2021-12-18T22:37:37.9225770Z     raise IOError("ERROR: %s [%s] not found!" % (name, path))
2021-12-18T22:37:37.9226890Z OSError: ERROR: Data file [/tmp/mbedtls-20211218-25035-1043085/mbedtls-mbedtls-3.1.0/build/tests/suites/test_suite_psa_crypto_storage_format.v0.data] not found!
2021-12-18T22:37:37.9227850Z make[2]: *** [tests/test_suite_psa_crypto_storage_format.v0.c] Error 1
```

So `generate_test_code.py` can't find `test_suite_psa_crypto_storage_format.v0.data` even though it has been successfully re-generated above. With the mixture of absolute and relative paths in the logs, it's not clear to me at this time whether the file was generated in the same directory where the build later expects it.

I also see `Deleting primary custom command output "/tmp/mbedtls-20211218-25035-1043085/mbedtls-mbedtls-3.1.0/build/tests/suites/test_suite_psa_crypto_generate_key.generated.data" because another output "/tmp/mbedtls-20211218-25035-1043085/mbedtls-mbedtls-3.1.0/build/tests/suites/test_suite_psa_crypto_storage_format.v0.data" does not exist.`, which doesn't seem to be a problem here but is not something I'd expect to see. Those two files are generated by the same command, so either both should exist or neither, unless it's a race condition while the generation script is running.

Can you please try one of the following workarounds?

* Do a non-parallel build. We've had bugs with parallel builds before due to accidentally missing dependencies (and also apparently due to a bug in older cmake versions, but that shouldn't be an issue with Homebrew).
* Pass `-DGEN_FILES=OFF` to cmake. This should use the generated files from the archive. (And I think it should be the default in the release, both with make and with cmake.)

**Comment by yuhaoth** [comment]
Please try if #5429 can fix this problem.

**Comment by chenrui333** [comment]
> Pass -DGEN_FILES=OFF to cmake. This should use the generated files from the archive. (And I think it should be the default in the release, both with make and with cmake.)

This fixed our build issue and we have merged the PR. Thanks @gilles-peskine-arm!

Closing the issue for now.

**Comment by gilles-peskine-arm** [comment]
I'm reopening this issue because there's a workaround for releases (and it won't need to be applied explicitly once we fix #5432), but that workaround doesn't apply to the development branch. We need to fix that (https://github.com/ARMmbed/mbedtls/pull/5429).

**Comment by chenrui333** [comment]
I see, make sense.
